@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
REM Generated by Vivado on Sat Oct 06 12:18:15 +0300 2018
=======
REM Generated by Vivado on Thu Oct 04 22:31:27 +0300 2018
>>>>>>> parent of 9f234ae... testbench
=======
REM Generated by Vivado on Thu Oct 04 22:31:27 +0300 2018
>>>>>>> parent of 9f234ae... testbench
=======
REM Generated by Vivado on Thu Oct 04 22:31:27 +0300 2018
>>>>>>> parent of 9f234ae... testbench
=======
REM Generated by Vivado on Thu Oct 04 22:31:27 +0300 2018
>>>>>>> parent of 9f234ae... testbench
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim cpu1_behav -key {Behavioral:sim_1:Functional:cpu1} -tclbatch cpu1.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
