# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
<<<<<<< HEAD
=======
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
>>>>>>> 9f234ae7243396eb0e45841a488f94b5c496e2b7
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
<<<<<<< HEAD
set_property webtalk.parent_dir C:/Users/USER/Desktop/cgj/cpu1/project_4/project_4.cache/wt [current_project]
set_property parent.project_path C:/Users/USER/Desktop/cgj/cpu1/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/USER/Desktop/cgj/cpu1/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/USER/Desktop/cgj/cpu1/project_4/project_4.srcs/sources_1/new/cpu1.v
=======
set_property webtalk.parent_dir C:/Users/Ibrahem/Desktop/hardware/project_4/project_4.cache/wt [current_project]
set_property parent.project_path C:/Users/Ibrahem/Desktop/hardware/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Ibrahem/Desktop/hardware/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/Ibrahem/Desktop/hardware/project_4/project_4.srcs/sources_1/new/cpu1.v
>>>>>>> 9f234ae7243396eb0e45841a488f94b5c496e2b7
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top cpu1 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu1_utilization_synth.rpt -pb cpu1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
